ADD SEARCHER text and open office hours
BigDataBiology/big-data-biology_org pull request #52
Opened 2024-03-29 00:01 UTC by Vedanth-Ramji

2024-03-29 00:20 UTC, luispedro commented
@cocodyq: can you fix the deployment error?

2024-03-29 01:07 UTC, Vedanth-Ramji commented
I found this issue: https://github.com/ryan-haskell/date-format/issues/40#issue-2183844717.

I tried `elm-json upgrade` but that didn't resolve the problem for me.

2024-03-30 05:47 UTC, luispedro commented
Can you rebase this to the current master to generate the preview?

2024-03-30 05:50 UTC, luispedro requested changes

2024-03-30 05:50 UTC, luispedro commented on content/open-office-hours.md
> +- [April 24, 2024 08:30am AEST (GMT+10.00)](https://qut.zoom.us/meeting/register/tZcsfuCopjwoHdBhmkJQY9mzd0Zu_LYCxrcv#/registration)
Can you add some info on what the time is in India/Berlin/New York/LA? or a link to the right https://everytimezone.com/ time

2024-04-02 02:44 UTC, merged